---
title: "COVID-19 Case Fatality Rate: South Korea"
#author: "Byungwon Kim"
date: "7/28/2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Code_functions_SCFR.r")
C <- read.csv("Korea/Korea_Agegroup_Cured.csv", header = TRUE, row.names = 1)
D <- read.csv("Korea/Korea_Agegroup_Dead.csv", header = TRUE, row.names = 1)
U <- read.csv("Korea/Korea_Agegroup_Unknown.csv", header = TRUE, row.names = 1)
N <- read.csv("Korea/Korea_Agegroup_Confirmed.csv", header = TRUE, row.names = 1)
#C[2]=rowSums(C[1:2])
#D[2]=rowSums(D[1:2])
#U[2]=rowSums(U[1:2])
#N[2]=rowSums(N[1:2])
#C = C[2:ncol(C)]
#D = D[2:ncol(D)]
#U = U[2:ncol(U)]
#N = N[2:ncol(N)]
colnames(C) <- c("0s","10s","20s","30s","40s","50s","60s","70s","80s")
colnames(D) <- c("0s","10s","20s","30s","40s","50s","60s","70s","80s")
colnames(U) <- c("0s","10s","20s","30s","40s","50s","60s","70s","80s")
colnames(N) <- c("0s","10s","20s","30s","40s","50s","60s","70s","80s")

#C = C[which(rownames(C)=="2020-03-25"):nrow(C),]
#D = D[which(rownames(D)=="2020-03-25"):nrow(D),]
#U = U[which(rownames(U)=="2020-03-25"):nrow(U),]
#N = N[which(rownames(N)=="2020-03-25"):nrow(N),]


FR.ours <- SCFR_estimation(D = D, U = U, C = C, N = N, model.option = 1)
FR.WHO1 <- SCFR_estimation(D = D, U = U, C = C, N = N, model.option = 4)


FR.ours.collapsed <- SCFR_estimation(D = matrix(apply(D,1,sum), ncol = 1),
                                     U = matrix(apply(U,1,sum), ncol = 1),
                                     C = matrix(apply(C,1,sum), ncol = 1),
                                     N = matrix(apply(N,1,sum), ncol = 1), 
                                     model.option = 1)


```

## Trend of Daily Gross Case Fatality Rate

```{r figure_1_CFR, echo = FALSE, fig.height = 7, fig.width = 12}
y.limit <- c(0, max(FR.ours$gross,
                    FR.WHO1$gross, 
                    FR.ours.collapsed$gross) + 0.02)
nt <- nrow(D)
days <- rownames(D)

par(mar = c(8,7,5,3))

FR.ours$gross.lower[FR.ours$gross.lower<0]=0
FR.ours$group.lower[FR.ours$group.lower<0]=0
FR.ours.collapsed$group.lower[FR.ours.collapsed$group.lower<0]=0
FR.ours.collapsed$gross.lower[FR.ours.collapsed$gross.lower<0]=0

plot(1:nt, FR.ours$gross, 
     type = "n", ylim = y.limit, xlim = c(0, nt + 1),
     ylab = "", xlab = "", xaxt = "n", yaxt = "n", cex.lab = 1.5)
polygon(c(1:nt, rev(1:nt)), c(FR.ours$gross.lower, rev(FR.ours$gross.upper)), 
        border = NA, col = t_col("red", alpha = 0.6))
polygon(c(1:nt, rev(1:nt)), 
        c(FR.ours.collapsed$gross.lower, rev(FR.ours.collapsed$gross.upper)), 
        border = NA, col = t_col("dodgerblue", alpha = 0.6))
lines(1:nt, FR.WHO1$gross, type = "l", lty = 2, lwd = 2, col = "black",
      ylab = "", xlab = "")
lines(1:nt, FR.ours$gross, type = "l", lty = 1, lwd = 2, col = "red",
      ylab = "", xlab = "")
lines(1:nt, FR.ours.collapsed$gross, type = "l", lty = 1, lwd = 2, col = "dodgerblue",
      ylab = "", xlab = "")



legend("topright", 
       c("Naive CFR = # deaths / # confirmed", 
         "Our model - Age group stratification",
         "Our model - No group"), 
       col = c("black", "red", "dodgerblue"), 
       lty = c(2,1,1),
       lwd = c(2,2,2),
       cex = 1)
axis(side = 1, at = c(1, seq(15, length(days)-1, by = 15), length(days)),
     labels = days[c(1, seq(15, length(days)-1, by = 15), length(days))],
     las = 2, cex.axis = 1.3)
axis(side = 2, at = seq(0, round(y.limit[2],2), by = 0.01),
     labels = paste0(seq(0, round(y.limit[2] * 100, 0), by = 1), "%"),
     las = 1, cex.axis = 1.3)

```

## Latest Age Group-wise Case Fatality Rates as of 7 / 28 / 2020
```{r figure_2_agegroup_ci, echo = FALSE, fig.height = 7, fig.width = 12}
k <- 0
while(k < 10){
  k <- k + 1
  if (10^k < 2*max(N[nrow(N),]) & 2*max(N[nrow(N),]) < 10^(k+1)) break
}
max_x_lim <- 10^(k+1)

par(mar = c(4, 8, 5, 3))
plot(0, 0, type = "n", ylim = c(0, 10.5), xlim = c(-max_x_lim, 0),
     ylab = "", xlab = "",
     xaxt = "n", yaxt = "n")
for (i in 1:9){
  polygon(c(-N[nrow(N), i], 0, 0, -N[nrow(N), i]),
          c(10.5 - i, 10.5 - i, 10.5 - (i+1), 10.5 - (i+1)), 
          border = "grey", col = t_col("grey", alpha = 0.6))
}
axis(side = 1, at = -seq(0, max_x_lim, length.out = 5),
     labels = seq(0, max_x_lim, length.out = 5),
     las = 1, cex.axis = 1.5, line = 0)

max_cfr_lim <- 2*max(FR.ours$group[length(days),])

par(mar = c(4, 8, 5, 3),new = T)

plot(seq(0, max(FR.ours$group.upper)+0.05, length.out = 11),
     seq(0:10), type = "n", ylim = c(0,10.5), xlim = c(0, max_cfr_lim),
     ylab = "", xlab = "", 
     xaxt = "n", yaxt = "n")

points(FR.ours$gross[length(days)], 10, pch = 1, lwd = 10, col = "dodgerblue")

points(FR.WHO1$gross[length(days)], 10, pch = 23, lwd = 5, col = "red")

lines(c(FR.ours$gross.lower[length(days)],
        FR.ours$gross.upper[length(days)]),
      rep(10, 2),
      type = "b", lty = 1, pch = c(91,93), lwd = 5, col = "seagreen")
for(i in 1:9){
  points(FR.ours$group[nrow(FR.ours$group),i], i, pch = 1, lwd = 10, col = "dodgerblue")
  points(FR.WHO1$group[nrow(FR.WHO1$group),i], i, pch = 23, lwd = 5, col = "red")
  lines(c(FR.ours$group.lower[nrow(FR.ours$group),i], 
          FR.ours$group.upper[nrow(FR.ours$group),i]),
        rep(i, 2), 
        type = "b", lty = 1, pch = c(91,93), lwd = 5, col = "seagreen")
}

axis(side = 3, at = seq(0, max_cfr_lim, by = 0.1),
     labels = paste0(seq(0, max_cfr_lim*100, by = 10), "%"),
     las = 1, cex.axis = 1.5)
axis(side = 2, at = 1:10,
     labels = c("0 - 9", "10 - 19","20 - 29", "30 - 39", "40 - 49",
                "50 - 59", "60 - 69", "70 - 79", "over 80", "Gross"),
     las = 2, cex.axis = 1.5)
title(ylab = "Age", line = 6.5, cex.lab = 1.7)
title(xlab = "# of confirmed cases", line = 2.5, cex.lab = 1.7)
title(main = "CFR", line = 3, cex.main=1.7)
legend("topright", legend = c("Our model", "Naive CFR"),
       col = c("dodgerblue", "red"),
       pch = c(1,23), cex = 1, lwd = 5, lty = 0)
```


```{r table_1_CFR, echo = FALSE}
library(DT)
Today <- length(FR.ours$gross)
CFR.Gross.table <- data.frame(Confirmed = c(sum(as.numeric(N[Today,])),
                                            as.numeric(N[Today,])),
                              WHO1 = c(round(as.numeric(FR.WHO1$gross[Today])*100,2),
                                       round(as.numeric(FR.WHO1$group[Today,])*100,2)),
                              CFR = c(round(as.numeric(FR.ours$gross[Today]) * 100, 2),
                                      round(as.numeric(FR.ours$group[Today,]) * 100, 2)),
                              SE = c(round(sqrt(as.numeric(FR.ours$gross.variance[Today])) * 100, 2),
                                     round(sqrt(as.numeric(FR.ours$group.variance[Today,])) * 100, 2)),
                              Lower = c(round(as.numeric(FR.ours$gross.lower[Today]) * 100, 2),
                                        round(as.numeric(FR.ours$group.lower[Today,]) * 100, 2)),
                              Upper = c(round(as.numeric(FR.ours$gross.upper[Today]) * 100, 2),
                                        round(as.numeric(FR.ours$group.upper[Today,]) * 100, 2)))
colnames(CFR.Gross.table) <- c("Confirmed",
                               "Naive CFR (%)",
                               "Fatality Rate Estimate (%)", 
                               "SE (%)", 
                               "LB (%)", 
                               "UB (%)")
rownames(CFR.Gross.table) <- c("Gross", colnames(FR.ours$group))
datatable(CFR.Gross.table, options = list(pageLength = 9))
```

## Cumulative number of recovered patients (estimated)

```{r table_4_recovered, echo = FALSE}
C.table <- data.frame(Date = rownames(C),
                      Total = apply(C, 1, sum),
                      C)
colnames(C.table) <- c("Date", "Total", colnames(C))
rownames(C.table) <- c()
datatable(C.table[nrow(C.table):1,], options = list(pageLength = 5))
```

##### *Data source*
* ###### *Daily updated age grouped data can be downloaded from the below link:*
  ###### https://www.kaggle.com/kimjihoo/coronavirusdataset#TimeAge.csv
  * ###### *If not properly updated, the data can be manually recorded from the daily report published by KCDC*
  ###### http://ncov.mohw.go.kr/tcmBoardList.do?brdId=3&brdGubun=&dataGubun=&ncvContSeq=&contSeq=&board_id=
