---
title: "COVID-19 Case Fatality Rate: Global"
#author: "Byungwon Kim"
date: "7/26/2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Code_functions_SCFR.r")
Country <- read.csv("Raw/Country_name.csv", header = TRUE)
setwd("Global")  
C <- read.csv("Global_Cured.csv", header = TRUE, row.names = 1)
D <- read.csv("Global_Dead.csv", header = TRUE, row.names = 1)
U <- read.csv("Global_Unknown.csv", header = TRUE, row.names = 1)
N <- read.csv("Global_Confirmed.csv", header = TRUE, row.names = 1)
Country.name <- as.character(Country$Country)
colnames(C) <- Country.name
colnames(D) <- Country.name
colnames(U) <- Country.name
colnames(N) <- Country.name

C[] = lapply(C,as.numeric)
D[] = lapply(D,as.numeric)
U[] = lapply(U,as.numeric)
N[] = lapply(N,as.numeric)

FR.ours <- SCFR_estimation(D = D, U = U, C = C, N = N, model.option = 1)
FR.WHO1 <- SCFR_estimation(D = D, U = U, C = C, N = N, model.option = 4)
```

## Trend of Daily Gross Case Fatality Rate

```{r figure_1_CFR, echo = FALSE, fig.height = 7, fig.width = 12}
y.limit <- c(-0.01, max(FR.ours$gross, 
                        FR.WHO1$gross) + 0.2)
nt <- nrow(D)
days <- rownames(C)



par(mar = c(8,7,5,3))

FR.ours$gross.lower[FR.ours$gross.lower<0]=0
FR.ours$group.lower[FR.ours$group.lower<0]=0
plot(1:nt, FR.ours$gross, 
     type = "n", ylim = y.limit, xlim = c(0, nt + 1),
     ylab = "", xlab = "", xaxt = "n", yaxt = "n", cex.lab = 1.5)
polygon(c(1:nt, rev(1:nt)), c(FR.ours$gross.lower, rev(FR.ours$gross.upper)), 
        border = NA, col = t_col("red", alpha = 0.6))
polygon(c(1:nt, rev(1:nt)), 
        c(FR.ours$group.lower[,"Korea, South"], rev(FR.ours$group.upper[,"Korea, South"])), 
        border = NA, col = t_col("blue", alpha = 0.6))
polygon(c(1:nt, rev(1:nt)), 
        c(FR.ours$group.lower[,"Italy"], rev(FR.ours$group.upper[,"Italy"])), 
        border = NA, col = t_col("seagreen", alpha = 0.6))
polygon(c(1:nt, rev(1:nt)), 
        c(FR.ours$group.lower[,"China"], rev(FR.ours$group.upper[,"China"])), 
        border = NA, col = t_col("pink", alpha = 0.6))
lines(1:nt, FR.WHO1$gross, type = "l", lty = 2, lwd = 2, col = "black",
      ylab = "", xlab = "")
lines(1:nt, FR.ours$gross, type = "l", lty = 1, lwd = 2, col = "red",
      ylab = "", xlab = "")
lines(1:nt, FR.ours$group[,"Korea, South"], type = "l", lty = 1, lwd = 2, col = "blue",
      ylab = "", xlab = "")
lines(1:nt, FR.ours$group[,"Italy"], type = "l", lty = 1, lwd = 2, col = "seagreen",
      ylab = "", xlab = "")
lines(1:nt, FR.ours$group[,"China"], type = "l", lty = 1, lwd = 2, col = "purple",
      ylab = "", xlab = "")

legend("topleft", 
       c("Naive CFR = # deaths / # confirmed", 
         "Our model - Country stratification",
         "Our model - Korea, South",
         "Our model - Italy",
         "Our model - China"), 
       col = c("black", "red", "blue", "seagreen","purple"), 
       lty = c(2,1,1,1,1),
       lwd = c(2,2,2,2,2),
       cex = 1.2)
axis(side = 1, at = c(1, seq(15, length(days)-1, by = 15), length(days)),
     labels = days[c(1, seq(15, length(days)-1, by = 15), length(days))],
     las = 2, cex.axis = 1.3)
axis(side = 2, at = seq(0, y.limit[2], by = 0.05),
     labels = paste0(seq(0, round(y.limit[2] * 100, 0), by = 5), "%"),
     las = 1, cex.axis = 1.3)

```

## Latest Country-wise Case Fatality Rates (TOP 10 countries in No. confirmed patients) as of 7 / 26 / 2020

```{r figure_2_Country_ci, echo = FALSE, fig.height = 7, fig.width = 12}
TOP10.index <- order(N[nrow(N),], decreasing = TRUE)[1:10]
TOP10.CFR <- FR.ours$group[nrow(N), TOP10.index]
TOP10.CFR.upper <- FR.ours$group.upper[nrow(N), TOP10.index]
TOP10.CFR.lower <- FR.ours$group.lower[nrow(N), TOP10.index]
CFR.order <- order(TOP10.CFR, decreasing = TRUE)

k <- 0
while(k < 10){
  k <- k + 1
  if (10^k < 2*max(N[nrow(N),]) & 2*max(N[nrow(N),]) < 10^(k+1)) break
}
max_x_lim <- 10^(k+1)
if (max(N[nrow(N),]) < max_x_lim / 4) max_x_lim <- max_x_lim / 2

# if histogram does not look good, manually choose the limit
#max_x_lim <- 120000

par(mar = c(4, 10, 5, 3))
plot(0, 0, type = "n", ylim = c(0, 11.5), xlim = c(-max_x_lim, 0),
     ylab = "", xlab = "",
     xaxt = "n", yaxt = "n")
for (i in 1:10){
  polygon(c(-N[nrow(N), TOP10.index[CFR.order[i]]], 0, 0, -N[nrow(N), TOP10.index[CFR.order[i]]]),
          c(11.5 - i, 11.5 - i, 11.5 - (i+1), 11.5 - (i+1)), 
          border = "grey", col = t_col("grey", alpha = 0.6))
}
axis(side = 1, at = -seq(0, max_x_lim, length.out = 5),
     labels = seq(0, max_x_lim, length.out = 5),
     las = 1, cex.axis = 1.5, line = 0)

max_cfr_lim <- 2*max(TOP10.CFR)

par(mar = c(4, 10, 5, 3),new = T)
plot(seq(0, 0.25, length.out = 12),
     seq(0:11), type = "n", ylim = c(0,11.5), xlim = c(0, max_cfr_lim),
     ylab = "", xlab = "",
     xaxt = "n", yaxt = "n")
points(FR.ours$gross[length(days)], 11, pch = 1, lwd = 10, col = "dodgerblue")
points(FR.WHO1$gross[length(days)], 11, pch = 23, lwd = 5, col = "red")

lines(c(FR.ours$gross.lower[length(days)],
        FR.ours$gross.upper[length(days)]),
      rep(11, 2),
      type = "b", lty = 1, pch = c(91,93), lwd = 5, col = "seagreen")
for(i in 1:10){
  points(TOP10.CFR[CFR.order[i]], 11 - i, pch = 1, lwd = 10, col = "dodgerblue")
  points(FR.WHO1$group[nrow(FR.WHO1$group),TOP10.index][CFR.order[i]], 11 - i, pch = 23, lwd = 5, col = "red")
  lines(c(TOP10.CFR.lower[CFR.order[i]], 
          TOP10.CFR.upper[CFR.order[i]]),
        rep(11 - i, 2), 
        type = "b", lty = 1, pch = c(91,93), lwd = 5, col = "seagreen")
}
axis(side = 3, at = seq(0, max_cfr_lim, by = 0.05),
     labels = paste0(seq(0, max_cfr_lim*100, by = 5), "%"),
     las = 1, cex.axis = 1.5)

axis(side = 2, at = 11:1,
     labels = c("Gross", names(TOP10.CFR)[CFR.order]),
     las = 2, cex.axis = 1.5)

title(xlab = "# of confirmed cases", line = 2.5, cex.lab = 1.7)
title(main = "CFR", line = 3, cex.main = 1.7)
legend("topright", legend = c("Our model", "Naive CFR"),
       col = c("dodgerblue", "red"),
       pch = c(1,23), cex = 1, lwd = 4, lty = 0)

```

```{r table_1_CFR, echo = FALSE}
library(DT)
Today <- length(FR.ours$gross)
CFR.Gross.table <- data.frame(Confirmed = c(sum(as.numeric(N[Today,])),
                                            as.numeric(N[Today,])),
                              WHO1 = c(round(as.numeric(FR.WHO1$gross[Today])*100,2),
                                       round(as.numeric(FR.WHO1$group[Today,])*100,2)),
                              CFR = c(round(as.numeric(FR.ours$gross[Today]) * 100, 2),
                                      round(as.numeric(FR.ours$group[Today,]) * 100, 2)),
                              SE = c(round(sqrt(as.numeric(FR.ours$gross.variance[Today])) * 100, 2),
                                     round(sqrt(as.numeric(FR.ours$group.variance[Today,])) * 100, 2)),
                              Lower = c(round(as.numeric(FR.ours$gross.lower[Today]) * 100, 2),
                                      round(as.numeric(FR.ours$group.lower[Today,]) * 100, 2)),
                              Upper = c(round(as.numeric(FR.ours$gross.upper[Today]) * 100, 2),
                                      round(as.numeric(FR.ours$group.upper[Today,]) * 100, 2)))
colnames(CFR.Gross.table) <- c("Confirmed",
                               "Naive CFR (%)",
                               "Fatality Rate Estimate (%)", 
                               "SE (%)", 
                               "LB (%)", 
                               "UB (%)")
rownames(CFR.Gross.table) <- c("--Global Gross--", colnames(FR.ours$group))
order.table <- order(N[nrow(N),], decreasing = T)
datatable(CFR.Gross.table[c(1, order.table+1),], options = list(pageLength = 10))
```

##### *Data source*
  * ###### *Daily updated global data can be downloaded from the below link:*
    ###### https://github.com/CSSEGISandData/COVID-19

