---
title: "COVID-19 Case Fatality Rate in South Korea"
#author: "Byungwon Kim"
date: "3/27/2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Methods
  * ### The presented age group-wise CFRs (Case Fatality Rates) are calculted using the below method in age groups separately, and the gross CFR is the weighted average of group-wise CFRs
    + #### The CFR at time $t$ is estimated by
      #### $$ \widehat{FR}(t) = \frac{\mbox{No. deceased patients }(t) + \mbox{Expected No. deaths in future}}{\mbox{No. confirmed patients }(t)} $$
    + #### Here, the 'Expected No. deaths in future' is calculated by
      #### $$ \mbox{Expected No. deaths in future} = \mbox{No. quarantined patients} (t) \times p_d $$
    + #### $p_d$ denotes the probability of death and is estimated by the number of deceased patients divided by the number of confirmed patients at time $t$
 

## Backgrounds
  * #### There are 2 representative methods in calculating the CFR that WHO (World Health Organization) recommends to use
    + #### 1. Proportion of deceased patients among the infected (practically, diagnostic-confirmed) patients
    #### $$ FR_{WHO_1} = \frac{\mbox{No. deceased patients}}{\mbox{No. confirmed patients}} $$
    + #### 2. Proportion of deceased patients among the deceased and recovered patients
    #### $$ FR_{WHO_2} = \frac{\mbox{No. deceased patients}}{\mbox{No. deceased patients + No. recovered patients}} $$
  * #### When the prevalence of epidemic disease is over, the two CFRs above become equal
  * #### However, during the prevalence, the 1st one 'underestimates' the case fatality rate while the 2nd one 'overestimates' it

## R codes
  * #### https://github.com/sungkyujung/covid19cfr
